---
- name: Flatpak
  tags: [role-flatpak]
  block:

  - ansible.builtin.import_tasks: flatpak-install.yml
  - ansible.builtin.import_tasks: flatpak-install-apps.yml
  
  - name: Process systemd unit configurations
    ansible.builtin.include_tasks: flatpak-systemd-unit.yml
    loop: "{{ flatpak_systemd_units }}"
    loop_control:
      loop_var: item
      label: "{{ unit_item.name }}"